server:
  port:7075
  
spring:
    #DB properties
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Hibernate Properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #SMTP properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: vikas.devda2000@gmail.com
    password: aidf orgl bvyw xprh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#Kafka Properties
Kafka:
  topic:
    order: ecommerce_orders
  bootstrap-servers: localhost:9092
